SOURCE_DIR=$1
shift
./do-configure \
-DVERA_TRIBITS_DIR:PATH=$SOURCE_DIR/Trilinos/cmake/tribits \
-DVERA_TEST_CATEGORIES:STRING=NIGHTLY \
-DVERA_ENABLE_KNOWN_EXTERNAL_REPOS_TYPE=Continuous \
-DVERA_EXTRA_REPOSITORIES:STRING=TriBITS,Trilinos,TeuchosWrappersExt,Futility,MAMBA,VERAInExt,DataTransferKit,COBRA-TF,MOOSEExt,SCALE,MPACT,VeraShift,DakotaExt \
-DVERA_EXTRAREPOS_FILE=$SOURCE_DIR/cmake/ExtraRepositoriesList.cmake \
-DVERA_ENABLE_VRIPSScobra_preproc:BOOL=ON \
-DVERA_ENABLE_ALL_PACKAGES=ON \
-DVERA_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \
-DVERA_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=ON \
-DTPL_ENABLE_BLAS=ON -DBLAS_LIBRARY_DIRS:STRING="/home/tools/gcc-8.3.0/tpls/opt/lapack-3.3.1/lib" \
-DTPL_ENABLE_LAPACK=ON -DLAPACK_LIBRARY_DIRS:STRING="/home/tools/gcc-8.3.0/tpls/opt/lapack-3.3.1/lib" \
-DMPI_EXEC_MAX_NUMPROCS=36 \
$@
