#!/bin/bash
SRC_DIR=$1
$SRC_DIR/build_scripts/build_with_casl_env_540.sh $SRC_DIR/build_scripts/build_gnu_debug_serial_all.sh $SRC_DIR -DFutility_ENABLE_DBC=ON -DMPACT_BUILD_STANDARD=ON -DMPACT_ENABLE_DEBUG_MSG=ON -DMPACT_ENABLE_MPACT_HELIOSXS=OFF -DMPACT_ENABLE_COBRA_TF=OFF -DMPACT_ENABLE_DataTransferKit=OFF -DMPACT_ENABLE_PolarisMoonraker=OFF -DMPACT_ENABLE_Origen=OFF -DMPACT_ENABLE_Teuchos=OFF -DMPACT_WARN_ABOUT_MISSING_EXTERNAL_PACKAGES=TRUE -DMPI_EXEC_MAX_NUMPROCS:STRING=12
