#!/bin/bash
SRC_DIR=$1
$SRC_DIR/build_scripts/build_mpi_debug_all.sh $SRC_DIR  -DMPACT_ENABLE_DEBUG_MSG=ON -DMPACT_ENABLE_MPACT_HELIOSXS=OFF -DMPACT_ENABLE_mongoose=OFF -DMPACT_ENABLE_COBRA_TF=OFF -DMPACT_ENABLE_DataTransferKit=OFF -DMPACT_ENABLE_Origen=OFF -DMPACT_ENABLE_Teuchos=OFF -DMPI_EXEC_MAX_NUMPROCS:STRING=12
